### ISSUE TITLE
Problem with amazonaws.com

### ISSUE THREAD

**Issue by TomasAxelsson** [luckyrat/domain-public-suffix#2]
Hi, when use the .TryParse function and the URL is containing amazonaws.com it fails and returns null.

I guess the problem is that it does not handle the parts of https://publicsuffix.org/list/public_suffix_list.dat where there is *-signs correct.

// Amazon Elastic Compute Cloud: https://aws.amazon.com/ec2/
// Submitted by Luke Wells <psl-maintainers@amazon.com>
*.compute.amazonaws.com
*.compute-1.amazonaws.com
*.compute.amazonaws.com.cn
us-east-1.amazonaws.com

**Comment by luckyrat** [comment]
Yeah, support for wildcards was only implemented to the level required for the contents of the list at the time but there are some gaps compared to the full spec and it appears that there are now real world examples of this. I won't have time to work on this soon but would accept a pull request if someone wants to write some tests and an implementation to support this part of the spec.

**Comment by luckyrat** [comment]
I added a couple of tests for amazonaws.com and they appeared to work correctly straight away so it's possible that you had accessed a slightly out of date version of the PSL or maybe have expectations that didn't align with the official PSL description of amazonaws.com URLs as of a year ago.

I've not specifically looked into all of the many AWS rules in the PSL so it's possible that there are some examples beyond those you've listed which are failing with the 1.x version of this library.

I've just pushed a new version 2.x to the master branch which contains a variety of improvements so that it now aligns fully with the PSL spec (with the exception of one irrelevant point that no implementations currently support) so you should find this works for any type of AWS domain.

I'll close this now but please feel free to create a new issue with details of any remaining problem you have, including how to reproduce the problem (and ideally a test case that fails).
